# Generated by Django 4.0.1 on 2022-01-31 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DificultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.JSONField()),
                ('solution', models.JSONField()),
                ('dificultyLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.dificultylevel')),
            ],
        ),
    ]
