# Generated by Django 4.0.1 on 2022-01-31 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
