# Generated by Django 4.0.1 on 2022-01-31 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_puzzle_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="puzzle",
            name="solution",
        ),
        
        migrations.AddField(
            model_name='puzzle',
            name='solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=9), size=9),
        ),
    ]
