# Generated by Django 4.0.1 on 2022-01-31 15:48

import django.contrib.postgres.fields
from django.db import migrations, models
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_rename_question_puzzle_ques_remove_puzzle_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='ques',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='question',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=puzzles.models.get_default), size=9), default=puzzles.models.get_default, size=9),
        ),
    ]
