# Generated by Django 4.0.1 on 2022-02-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0006_remove_puzzle_ques_puzzle_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='question',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='sol',
        ),
    ]
