# Generated by Django 4.0.1 on 2022-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
         ('puzzles', '0008_puzzle_qrow1_puzzle_qrow2_puzzle_qrow3_puzzle_qrow4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='source',
            field=models.CharField(default='https://websudoku.com/', max_length=100),
        ),
    ]
