# Generated by Django 4.0.1 on 2022-03-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_remove_puzzle_srow1_remove_puzzle_srow2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='bestTime_minutes',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='bestTime_seconds',
        ),
        migrations.CreateModel(
            name='PlayingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('win_precentage', models.FloatField(default=0.0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('unsuccessful_attempts', models.IntegerField(default=0)),
                ('bestTime_minutes', models.IntegerField(default=0)),
                ('bestTime_seconds', models.IntegerField(default=0)),
                ('avg_bestTime_minutes', models.IntegerField(default=0)),
                ('avg_bestTime_seconds', models.IntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.dificultylevel')),
            ],
        ),
    ]
