# Generated by Django 4.0.1 on 2022-03-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0014_remove_puzzle_besttime_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playingdata',
            old_name='email',
            new_name='username',
        ),
    ]
