# Generated by Django 4.0.1 on 2022-03-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0015_rename_email_playingdata_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playingdata',
            old_name='win_precentage',
            new_name='success_precentage',
        ),
    ]
