# Generated by Django 4.0.1 on 2022-03-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0017_rename_success_precentage_playingdata_success_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playingdata',
            old_name='avg_bestTime_minutes',
            new_name='avg_Time_minutes',
        ),
        migrations.RenameField(
            model_name='playingdata',
            old_name='avg_bestTime_seconds',
            new_name='avg_Time_seconds',
        ),
    ]
