# Generated by Django 4.0.1 on 2022-03-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0019_remove_playingdata_avg_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dificultylevel',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dificultylevel',
            name='avg_Time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playingdata',
            name='worst_Time',
            field=models.IntegerField(default=0),
        ),
    ]
