# Generated by Django 4.0.1 on 2022-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0020_dificultylevel_attempts_dificultylevel_avg_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dificultylevel',
            name='number_of_empty_cells',
            field=models.IntegerField(default=0),
        ),
    ]
