# Generated by Django 4.0.1 on 2022-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0022_rename_successful_attempts_playingdata_correct_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playingdata',
            old_name='successrate',
            new_name='success_rate',
        ),
    ]
