# Generated by Django 4.0.4 on 2023-07-13 07:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0024_playingdata_solved_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingdata',
            name='solved_timings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
